# Copyright 2022 The MathWorks, Inc.

name: Run MATLAB Build
description: >-
  Run MATLAB build with the MATLAB Build Tool
inputs:
  tasks:
    description: >-
      Space separated list of tasks to execute
    required: false
    default: ""
runs:
  using: node16
  main: dist/index.js
