# Copyright 2022-2024 The MathWorks, Inc.

name: Run MATLAB Build
description: >-
  Run a build with the MATLAB build tool
inputs:
  tasks:
    description: >-
      Space-separated list of tasks to run
    required: false
    default: ""
  build-options:
    description: >-
      Build options for MATLAB build tool
    required: false
    default: ""
  startup-options:
    description: >-
      Startup options for MATLAB
    required: false
    default: ""
runs:
  using: node20
  main: dist/index.js
